name: wifi_info_ext
description: "A Flutter plugin to retrieve Wi-Fi network information (SSID, BSSID, IP) on Android and iOS."
version: 0.0.1
homepage: https://github.com/long-lt/wifi_info/
repository: https://github.com/long-lt/wifi_info
issue_tracker: https://github.com/long-lt/wifi_info/issues
publish_to: https://pub.dev/packages/wifi_info_ext

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tah.wifi_info
        pluginClass: WifiInfoPlugin
      ios:
        pluginClass: WifiInfoPlugin
