name: wifi_info_plus
description: A Flutter plugin to get WiFi SSID and BSSID on Android/iOS.

version: 0.0.1
homepage: https://github.com/long-lt/wifi_info
repository: https://github.com/long-lt/wifi_info

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.long.wifi_info_plus
        pluginClass: WifiInfoPlugin
      ios:
        pluginClass: WifiInfoPlugin
